# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# ModStitch Platform (default, will be overridden per version)
modstitch.platform=fabric-loom

# Mod Properties
mod_id=spatial-gui
mod_name=SpatialGUI
mod_version=1.0
mod_group=org.tastytrash
mod_description=A spatial GUI mod for Minecraft
mod_license=MIT
mod_author=tastytrash

# Minecraft Properties
deps.minecraft=26.2
supported_minecraft_versions=26.2,26.3-pre-1
minecraft_version_range=>=26.2
java_version=25

# Fabric Properties
deps.fabric_loader=0.19.3
deps.fabric_api=0.158.0+26.2
deps.modmenu=20.0.1
deps.cloth_config=26.2.155

# NeoForge Properties
deps.neoforge=26.2.59
neoforge_version_range=[26.2,)
