pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Stonecutter'
            url = "https://maven.kikugie.dev"
        }
        gradlePluginPortal()
    }
}

plugins {
    id "dev.kikugie.stonecutter" version "0.9.8"
}

stonecutter {
    create(rootProject) {
        versions '26.3-pre-1'
    }
}