pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'Stonecutter'
            url = "https://maven.kikugie.dev"
        }
        maven {
            name = 'KikuGie Releases'
            url = "https://maven.kikugie.dev/releases"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id "dev.kikugie.stonecutter" version "0.9.8"
    id "dev.kikugie.loom-back-compat" version "0.4"
}

stonecutter {
    create(rootProject) {
        vers("1.20.1-forge", "1.20.1")
        vers("1.20.1-fabric", "1.20.1")
        vers("1.21.1-neoforge", "1.21.1")
        vers("1.21.1-fabric", "1.21.1")
        vers("1.21.11-neoforge", "1.21.11")
        vers("1.21.11-fabric", "1.21.11")
        vers("26.1.2-fabric", "26.1.2")
        vers("26.1.2-neoforge", "26.1.2")
        vers("26.2-fabric", "26.2")
        vers("26.2-neoforge", "26.2")
        vers("26.3-fabric", "26.3")
        vers("26.3-neoforge", "26.3")
    }
}